tmux:
  symbols:
    branch: " "
    hashprefix: ":"
    ahead: "^"
    behind: "v"
    staged: "+"
    conflict: "!"
    modified: "~"
    untracked: "?"
    stashed: "*"
    clean: "ok"
  styles:
    clear: "#[fg=default]"
    state: "#[fg=colour210,bold]"
    branch: "#[fg=colour111,bold]"
    remote: "#[fg=colour60]"
    staged: "#[fg=colour149]"
    conflict: "#[fg=colour210]"
    modified: "#[fg=colour215]"
    untracked: "#[fg=colour60]"
    stashed: "#[fg=colour141]"
    clean: "#[fg=colour149]"
  layout:
    - branch
    - " "
    - remote-branch
    - divergence
    - " - "
    - flags
